global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: {{ env "LETSENCRYPT_EMAIL" }}
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
  cloudflare:
    acme:
      email: {{ env "LETSENCRYPT_EMAIL" }}
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

providers:
  docker:
    exposedByDefault: false
    network: camphish-net
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

api:
  dashboard: true
  insecure: false

log:
  level: INFO

accessLog: {}
